a=require
b=a('express')
e=b()
e.use(b.text())
g=a('fs')
e.get('',(r,s)=>s.sendFile(__dirname+"/i.htm"))
e.post('/c',(r,s)=>{d=r.body;e=a('md5')(d);g.writeFileSync(e,d);s.send(e)})
e.get('/:e',(r,s)=>s.redirect(g.readFileSync(r.params.e)))
e.listen(8069)