a=require;
b=a('express');
e=b();
c=JSON;
g=a('fs');
e.use(b.json());
e.get('',(r,s)=>s.sendFile(__dirname+"/i.htm"));
e.post('/c',(r,s)=>{d=r.body.u;e=a('js-sha512').sha512(d).slice(0,7);g.writeFileSync(e,`{"u":"${d}"}`);s.send(e)});
e.get('/:e',(r,s)=>s.redirect(c.parse(g.readFileSync(r.params.e)).u));
e.listen(8069)